### PR TITLE
Update PrimePussify.js

### PR DESCRIPTION
**Pull request by axjxwright**
Added simple UI, also retrieves font size from the active layer. Breaks the `PrevPuss` serialization as this was enough JS for me for a lifetime.

### CODE REVIEW

**Comment by cmuratori** [comment]
This is cool! Why does the scripting documentation say that you can't use these things in Photoshop when you obviously can, since you just did?? The reason I never tried them was because the scripting documentation said it was only available in other Adobe tools :(  I guess I'm not sure why I thought the docs would be accurate.

Anyway, I tried it out a little bit and I think there are a few issues that I'm not sure what the easiest way to solve would be:

* It's really hard to work with baseline variance now, because generally that wants to be floating-point and within a very narrow range (like 4.25, 4.6, etc.)
* The maximum value for spacing is too low, or would usually be too low - I think it's in pixels, basically, so it depends on the resolution of the image.
* In order to be usable, it really needs to save the last set of parameters so the artist can quickly apply the same pussification over and over again without having to reset it.

I can try to work on these myself - should I create a separate branch for this until it's ready, or do you want to look at it yourself first?

Best wishes,
\- Casey

**Comment by axjxwright** [comment]
Mate I was just bored in isolation (and was confused as to why you were saying you couldn't do UI in scripts when I was positive I'd done it before) so i just had a quick fiddle to see if it had changed. I'm happy for you to grab the code from the second commit and paste it into your master branch and reject the pull request. 

I'm not sure how the slider handles ranges, does it go by the min and max values? If you pass it a different range to the `MakeSlider` function does that change anything?

Back in the "day" I remember using a thing from adobe called the ExtendScript Toolkit. It was a dicky little IDE but it let you run and debug scripts directly rather than doing the while File > Scripts > Browse... round trip but more importantly it had semi-decent inline documentation for the particular incantations each of the creative suite would listen to. I'd suggest trying to track that down if you can. Otherwise if you can wait till next weekend I can have another look for you.

*edit Of course Adobe's download page just sends you into an endless loop of 404s and login redirects, but I managed to track down the installers [here](https://community.adobe.com/t5/get-started/how-can-i-download-extendscript-toolkit-for-cs6-in-the-creative-cloud/td-p/4564136?page=1)

Thanks for all the great content over the years by the way :)

A

**Comment by cmuratori** [comment]
I am pretty slammed at the moment so maybe it will just be "whoever gets to it first" :P  Either way, thank you very much for demonstrating that the scripts can open UI. I just naively believed the docs I read and so I never tried it. This opens up a whole new world of janky Photoshop scripting either way!

\- Casey

**Comment by cmuratori** [comment]
I've closed this pull request since someone actually went ahead and did the work for us based on this pull request :)  So that is good news!

\- Casey

**Pull request closed without merging**
